#######################################
############  usuário  ################
#######################################

# Criar usuário

GET http://localhost:8000/ 
######################

 
POST http://127.0.0.1:8000/usuario HTTP/1.1
content-type: application/json

{
    "id": 2,
    "nome": "teste",
    "email": "teste@hotmail.com",
    "senha": "123"
}


#######################################
# Pegar usuário
GET http://127.0.0.1:8000/usuario/1 HTTP/1.1
content-type: application/json

###

DELETE http://127.0.0.1:8000/usuario/2 HTTP/1.1

#######################################
############  endereço  ###############
#######################################

# Criar endereço
POST http://127.0.0.1:8000/usuario/endereco HTTP/1.1
content-type: application/json

{   "id":2,
    "rua": "sebastiao",
    "cep": "9kkjhg",
    "cidade": "São Paulo",
    "estado": "SP"
}

###

GET http://127.0.0.1:8000/usuario/endereco/2 HTTP/1.1
content-type: application/json
#######################################
############  produto  ################
#######################################

# Criar produto
POST http://127.0.0.1:8000/produto HTTP/1.1
content-type: application/json

{
    "id": 2,
    "nome": "Sorvete",
    "descricao": "Doce gelado",
    "preco": 9.99
}

###

DELETE http://127.0.0.1:8000/usuario/endereco/2 HTTP/1.1